package varviewer.client.varTable;

import varviewer.client.DetailsPanel;
import varviewer.client.VarListManager;
import varviewer.client.filters.FiltersPanel;

import com.google.gwt.dom.client.Style.Unit;
import com.google.gwt.user.client.ui.DockLayoutPanel;
import com.google.gwt.user.client.ui.FlowPanel;

/**
 * A simple container for a filters panel, VarTable, and Details panel..
 * @author brendanofallon
 *
 */
public class VariantDisplay extends FlowPanel {

	public VariantDisplay() {
		initComponents();
	}

	private void initComponents() {
		DockLayoutPanel filtersAndTablePanel = new DockLayoutPanel(Unit.PX);
		filtersPanel = new FiltersPanel();
		filtersAndTablePanel.addWest(filtersPanel, 250);
		filtersAndTablePanel.setStylePrimaryName("filterandtablepanel");

		varTable = new VarTable();

		filtersAndTablePanel.add(varTable);
		this.add(filtersAndTablePanel);

		DetailsPanel detailsPanel = new DetailsPanel();
		//details panel listens to variant selection events generated by the varTable
		varTable.addVariantSelectionListener(detailsPanel); 
		varManager.addListener(varTable);
		filtersPanel.addListener(varManager);
		this.add(detailsPanel);	
	}
	
	VarListManager varManager = VarListManager.getManager();
	FiltersPanel filtersPanel;
	VarTable varTable = null;
}
