package varviewer.client.varTable;

import java.util.List;

import varviewer.client.DetailsPanel;
import varviewer.client.VarListListener;
import varviewer.client.VarListManager;
import varviewer.client.filters.FiltersPanel;
import varviewer.shared.Variant;
import varviewer.shared.VariantFilter;

import com.google.gwt.dom.client.Style.Unit;
import com.google.gwt.user.client.ui.DockLayoutPanel;
import com.google.gwt.user.client.ui.FlowPanel;

/**
 * A simple container for a filters panel, VarTable, and Details panel..
 * @author brendanofallon
 *
 */
public class VariantDisplay extends FlowPanel implements VarListListener {

	public VariantDisplay() {
		initComponents();
	}
	
	/**
	 * Return a list of the currently used filters
	 * @return
	 */
	public List<VariantFilter> getActiveFilters() {
		return filtersPanel.getFilters();
	}

	private void initComponents() {
		DockLayoutPanel filtersAndTablePanel = new DockLayoutPanel(Unit.PX);
		filtersPanel = new FiltersPanel();
		filtersAndTablePanel.addWest(filtersPanel, 250);
		filtersAndTablePanel.setStylePrimaryName("filterandtablepanel");

		varTable = new VarTable();

		filtersAndTablePanel.add(varTable);
		this.add(filtersAndTablePanel);

		DetailsPanel detailsPanel = new DetailsPanel();
		//details panel listens to variant selection events generated by the varTable
		varTable.addVariantSelectionListener(detailsPanel); 
		varManager.addListener(this);
		filtersPanel.addListener(varManager);
		this.add(detailsPanel);	
	}

	@Override
	public void variantListUpdated(List<Variant> newVars) {
		varTable.setVariants(newVars);
		
		//Create a string with sample names for the new label text
		StringBuilder str = new StringBuilder();
		List<String> samples = varManager.getSampleNames();
		if (samples == null || samples.size()==0) {
			str.append("Unknown sample");
		}
		else {
			str.append(samples.get(0));
			for(int i=1; i<samples.size(); i++) {
				str.append(", " + samples.get(i));
			}
		}
		setSampleLabelText(str.toString());
	}
	
	/**
	 * Set the text of the sample label in the header above the variant table
	 * @param text
	 */
	public void setSampleLabelText(String text) {
		varTable.getHeader().setSampleName(text);
	}
	
	VarListManager varManager = VarListManager.getManager();
	FiltersPanel filtersPanel;
	VarTable varTable = null;

}
