package varviewer.client;

import java.util.List;

import varviewer.client.filters.FiltersPanel;
import varviewer.client.sampleView.SamplesView;
import varviewer.client.services.ExportService;
import varviewer.client.services.ExportServiceAsync;
import varviewer.client.services.SampleListService;
import varviewer.client.services.SampleListServiceAsync;
import varviewer.client.varTable.VarTable;
import varviewer.shared.VariantFilter;
import varviewer.shared.SampleInfo;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.core.shared.GWT;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.rpc.AsyncCallback;
import com.google.gwt.user.client.ui.FlowPanel;
import com.google.gwt.user.client.ui.RootPanel;

/**
 * Entry point classes define <code>onModuleLoad()</code>.
 */
public class VarViewer implements EntryPoint {
	

	  public void onModuleLoad() {
		initComponents();
		//loadVariants();
	  }
	  
	  private void initComponents() {
		  FlowPanel mainPanel = new FlowPanel();
		  
		  final SamplesView sampleView = new SamplesView();
		  mainPanel.add(sampleView);
		  
		  sampleListService.getSampleList(new AsyncCallback<List<SampleInfo>>() {

			@Override
			public void onFailure(Throwable caught) {
				Window.alert("Error retrieving sample list : "+ caught.getMessage());
				caught.printStackTrace();
			}

			@Override
			public void onSuccess(List<SampleInfo> result) {
				sampleView.setSampleList(result);
			}
			  
		  });
		  
		  
//		  DockLayoutPanel filtersAndTablePanel = new DockLayoutPanel(Unit.PX);
//		  filtersPanel = new FiltersPanel();
//		  filtersAndTablePanel.addWest(filtersPanel, 250);
//		  filtersAndTablePanel.setStylePrimaryName("filterandtablepanel");
//		  
//		  varTable = new VarTable();
//		  
//		  filtersAndTablePanel.add(varTable);
//		  mainPanel.add(filtersAndTablePanel);
//		  
//		  DetailsPanel detailsPanel = new DetailsPanel();
//		  //details panel listens to variant selection events generated by the varTable
//		  varTable.addVariantSelectionListener(detailsPanel); 
//		  varManager.addListener(varTable);
//		  filtersPanel.addListener(varManager);
//		  mainPanel.add(detailsPanel);

		  RootPanel.get().add(mainPanel);		  
	  }

	  private void loadVariants() {
		  varManager.setSample("HHT11");
		  List<VariantFilter> filters = filtersPanel.getFilters();
		  varManager.setFilters(filters);
		  
		  varManager.reloadIfRequired();
	  }

	SampleListServiceAsync sampleListService = (SampleListServiceAsync) GWT.create(SampleListService.class);

	  FiltersPanel filtersPanel;
	  VarListManager varManager = VarListManager.getManager();
	  VarTable varTable = null;
}

