package varviewer.client;

import java.util.List;

import varviewer.client.varTable.VarTable;
import varviewer.shared.Interval;
import varviewer.shared.Variant;
import varviewer.shared.VariantRequest;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.core.client.GWT;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.rpc.AsyncCallback;
import com.google.gwt.user.client.ui.FlowPanel;
import com.google.gwt.user.client.ui.HorizontalPanel;
import com.google.gwt.user.client.ui.RootPanel;

/**
 * Entry point classes define <code>onModuleLoad()</code>.
 */
public class VarViewer implements EntryPoint {
	

	  public void onModuleLoad() {

		  initComponents();
		loadVariants();

	  }
	  
	  private void initComponents() {
		  FlowPanel mainPanel = new FlowPanel();
		  
		  HorizontalPanel filtersAndTablePanel = new HorizontalPanel();
		  FiltersPanel filtersPanel = new FiltersPanel();
		  filtersAndTablePanel.add(filtersPanel);
		  filtersAndTablePanel.setStylePrimaryName("filterandtablepanel");
		  
		  varTable = new VarTable();
		  
		  filtersAndTablePanel.add(varTable);
		  mainPanel.add(filtersAndTablePanel);
		  
		  DetailsPanel detailsPanel = new DetailsPanel();
		  //details panel listens to variant selection events generated by the varTable
		  varTable.addVariantSelectionListener(detailsPanel); 
		  mainPanel.add(detailsPanel);
		  
		  RootPanel.get().add(mainPanel);		  
	  }
	  
	  private void loadVariants() {
		
		  VariantRequest req = new VariantRequest();
		  req.addSample("foo");
		  req.addInterval("1", new Interval(1000000, 5000000));
		  varRequestService.queryVariant(req, new AsyncCallback<List<Variant>>() {

			@Override
			public void onFailure(Throwable caught) {
				Window.alert("Error retrieving variants : " + caught.toString());
			}

			@Override
			public void onSuccess(List<Variant> result) {
				varTable.setVariants(result);
			}
			  
		  });
	}

	  VarTable varTable = null;
	VarRequestServiceAsync varRequestService = (VarRequestServiceAsync) GWT.create(VarRequestService.class);
}

